version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      pip-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/back"
    schedule:
      interval: "monthly"
    groups:
      back-docker-images:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/front"
    schedule:
      interval: "monthly"
    groups:
      front-docker-images:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
