- hosts: all

  tasks:
    - name: Install packages required for mininet to work
      ansible.builtin.apt:
        pkg:
          - openssh-client
          - python3-dev
          - bridge-utils
          - curl
          - wget
          - net-tools
          - netcat-openbsd
          - dnsutils
          - ifupdown
          - iproute2
          - iptables
          - iputils-ping
          - traceroute
          - mininet
          - tcpdump
          - git
          - python3-pip
          - python3-setuptools
          - python3-venv
          - gcc
          - make
          - libpcap-dev
          - libbsd-dev
        force_apt_get: true
        update_cache: true
        install_recommends: false
        state: latest
      become: true
      become_method: sudo

    - name: Install mimidump
      ansible.builtin.shell: |
        git clone https://github.com/mimi-net/mimidump.git
        cd mimidump && git checkout 32e6e5e && sudo make prefix=/usr install
        cd .. && rm -rf mimidump

    - name: Create mininet_dependencies directory
      ansible.builtin.shell: |
        sudo mkdir -p /opt/mininet_dependencies
        sudo rm -rf /var/lib/apt/lists/* 
        sudo touch /etc/network/interfaces
      args:
        chdir: /vagrant/

    - name: Create env
      ansible.builtin.shell:
        python3 -m venv venv
      args:
        chdir: /vagrant/

    - name: Install requirements
      ansible.builtin.pip:
        requirements: requirements.txt
        virtualenv: venv
        chdir: /vagrant/
        version: 23.3.1
