version: "3.9"

services:
  miminet:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: celery
    network_mode: "host"
    restart: always
    env_file:
      - .env
    environment:
      - celery_concurrency=${celery_concurrency}
      - queue_names=${queue_names}
    privileged: true