version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:latest
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always
    networks:
      - rabbitmq_network
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbitmq:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./metrics_collector.conf:/etc/rabbitmq/conf.d/20-management_agent.disable_metrics_collector.conf
    ports:
      - 15672:15672
      - 5672:5672
      - 4369:4369
      - 25672:25672
      - 35197:35197

networks:
  rabbitmq_network:
    name: rabbitmq_network
