[uwsgi]
logto = ./uwsgi.log
module = app:app
master = true
socket = :80
processes = 5
chmod-socket = 660
enable-threads = true
buffer-size = 32768
vacuum = true
die-on-term = true
harakiri = 300
http-timeout = 300
