name: Yandex and Telegram authentication and Miminet authorization tests

on:
  push:
  pull_request_target:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test_env
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        cache-dependency-path: uv.lock

    - name: Installing dependencies
      run: |
        uv sync --frozen

    - name: Running tests
      run: |
        source .venv/bin/activate
        cd front/src
        python -m pytest -vv .
      env:
          CLIENT_YANDEX: ${{ secrets.CLIENT_YANDEX }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
