name: Linter

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ['back', 'front']
    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          cache-dependency-path: uv.lock

      - name: Install system dependencies (back)
        if: ${{ matrix.node == 'back' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends mininet
          mkdir -p /opt/mininet_dependencies

      - name: Install dependencies
        run: |
          uv sync --frozen

      - name: Lint with mypy
        run: |
          uv run --frozen mypy --ignore-missing-imports ${{matrix.node}}

      - name: Format with black
        run: |
          uv run --frozen black --check --verbose --diff ${{matrix.node}}

      - name: Lint with flake8
        run: |
          uv run --frozen flake8 --count --verbose --max-line-length=88 --extend-ignore=E501,W391,C901,E203 --statistics ${{matrix.node}}
